[build]
  base = "client"
  publish = "client/dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "22"
  VITE_SERVER_URL = "https://real-time-communication-with-socket-io.onrender.com"
